### ISSUE TITLE
Trying to Compile sm-64 port, and I get this error related to the sdk

### ISSUE THREAD

**Issue by godreborn** [pspdev/pspsdk#100]
/usr/local/pspdev/psp/sdk/include/psptypes.h:41:41: error: conflicting types for ‘u32’; have ‘uint32_t’ {aka ‘long unsigned int’}

I'm not a coder, so I don't know how to fix this.

**Comment by fjtrujy** [comment]
That’s something to be probably changed on the sm64-port.
The port probably was done with a legacy toolchain version.

**Comment by godreborn** [comment]
thanks.  I'm trying an older version that can't find netinet/in.h.  it's from late 2020.  however, it's present in usr/include/netinet  I think I need to make a symlink, but I'm not sure where this is looking.

**Comment by wally4000** [comment]
Hi Godreborn,

Unfortunately this seems like an internal issue if the file is located in /usr/include, i'd seek advice from the devs involved in the PSP Super Mario 64 port.
