### ISSUE TITLE
Remove -G0 flag in build_prx.mak ?

### ISSUE THREAD

**Issue by pyroesp** [pspdev/pspsdk#132]
I've been working on plugins lately and using build_prx.mak to compile the source.
For some reason the `-G0` flag is in the `CFLAGS` of the build_prx.mak file and I don't think it should be in there.
https://github.com/pspdev/pspsdk/blob/dbe0b6e03eca7f1ac5ba1554342f6d432a37774f/src/base/build_prx.mak#L27

The one argument I have against it being there is that it messes with debugging the plugin using psplink and psp-addr2line.

Unless there's a specific reason why `-G0` has been added there I'm unaware of, I think it should be removed.

PS: Could be I'm just bad at using psplink too 🤷🏻‍♂️

**Comment by sharkwouter** [comment]
My guess is that the decision was made to make people explicitly set it when they need debugging info, but I don't really see a big downside to changing it tbh. Maybe someone else can correct me.

**Comment by pyroesp** [comment]
From the discord, it was mentioned that the `G` option is for global variables and MIPS related.
What I had looked at was `g0` which was debug stuff.

As this isn't an issue anymore (just a misunderstanding), I'll close the issue.
