### ISSUE TITLE
Wrong freetype path

### ISSUE THREAD

**Issue by Fewnity** [pspdev/pspsdk#134]
Hello,

There is a problem, we can't load **freetype** because of a wrong path.
Freetype folder is located at **pspdev\psp\include\freetype2\freetype**
I need to move the **freetype2** folder's content in the **include** folder to get freetype working.

**Comment by sharkwouter** [comment]
Thanks for the repost @Fewnity. I'm currently looking into how freetype2 is packaged for Debian and Ubuntu and it seems they also use the same directory structure. We also do not make changes to the build files. I'd rather not deviate from the standard for this library.

**Comment by wally4000** [comment]
I've confirmed that this is also the case with a manual build on macOS. The include directory makes a folder called freetype2 then the internal directories are created afterwards..

It's a little silly but I guess it works for them
