### ISSUE TITLE
`__retarget_lock_init.o,  error: invalid type argument of ‘->’`

### ISSUE THREAD

**Issue by annadostoevskaya** [pspdev/pspsdk#146]
```
  CC       __retarget_lock_init.o
../../../src/libcglue/lock.c: In function ‘__retarget_lock_init’:
../../../src/libcglue/lock.c:31:36: error: invalid type argument of ‘->’ (have ‘_LOCK_T’ {aka ‘int’})
   31 |     sceKernelCreateLwMutex(&(*lock)->mutex, "lock API mutex", 0, 0, 0);
      |                                    ^~
```

What's went wrong? Maybe change compiler?
It's arch linux.

Install psp-gcc and try psp-sdk.
`paru psp-sdk`

also download latest version from github, and try again, same error

**Comment by sharkwouter** [comment]
What code are you trying to compile?

**Comment by annadostoevskaya** [comment]
i'm build current `master` psp-sdk !

i'm try install it with `paru psp-sdk`

**Comment by diamant3** [comment]
Hi, I don't have exp in arch but i think they don't have support for paru, if you building the pspsdk from github, try this instead https://github.com/pspdev/pspsdk#installation-from-git

**Comment by annadostoevskaya** [comment]
>also download latest version from github, and try again, same error

**Comment by diamant3** [comment]
hhmm, maybe try this instead https://github.com/pspdev/pspdev
