### ISSUE TITLE
Environmental Variables

### ISSUE THREAD

**Issue by godreborn** [pspdev/pspsdk#148]
hello.  I'm having an issue compiling infinity, and I think it may have something to do with environmental variables.  it can't find pspstub.s.  is there a specific environmental variable for this file or the include path in /usr/local/pspdev/psp/sdk/include ?  thank you.

**Comment by sharkwouter** [comment]
This should be included by default. Did you follow the instructions here to install PSPDEV?: https://pspdev.github.io/

**Comment by diamant3** [comment]
Maybe he tried to compile it using just `cmake` command, please try `psp-cmake` instead.

**Comment by godreborn** [comment]
thanks.  I figured it out a few weeks ago.  yeah, that was the problem (just using cmake instead of psp-cmake).  I was able to compile it afterwards with a few tweaks to the code.

**Comment by sharkwouter** [comment]
Good to hear, thanks for the update
