### ISSUE TITLE
undefined reference to `sceKernelVolatileMemTryLock'

### ISSUE THREAD

**Issue by taba256** [pspdev/pspsdk#151]
Hello.
I'm trying to use `sceKernelVolatileMemTryLock`, but it fails to compile.
main.c:
```c
#include <pspkernel.h>
#include <pspsuspend.h>

PSP_MODULE_INFO("template", 0, 1, 1);

PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);

int main()
{
	sceKernelVolatileMemTryLock(0, NULL, NULL);

	return 0;
}
```
result:
```
psp-gcc -I. -I/home/taba/pspdev/psp/include -I/home/taba/pspdev/psp/sdk/include -G0 -O2 -Wall -D_PSP_FW_VERSION=150  -L. -L/home/taba/pspdev/psp/lib -L/home/taba/pspdev/psp/sdk/lib  -Wl,-zmax-page-size=128  main.o  -lpspdebug -lpspdisplay -lpspge -lpspctrl -lpspnet -lpspnet_apctl -o template.elf
/home/taba/pspdev/bin/../lib/gcc/psp/11.2.0/../../../../psp/bin/ld: main.o: in function `main':
(.text.startup+0x10): undefined reference to `sceKernelVolatileMemTryLock'
collect2: エラー: ld はステータス 1 で終了しました
make: *** [/home/taba/pspdev/psp/sdk/lib/build.mak:162: template.elf] エラー 1
```

This typo is causing the problem.
https://github.com/pspdev/pspsdk/blob/e20ebe38220705abcbd6693ee2161170fb9665f1/src/user/Makefile.am#L21C141-L21C164

**Comment by diamant3** [comment]
You are right. I tried to reinstall pspsdk with a fix for the typo, and your code builds correctly. Anyway, if you want to make a PR for this issue, please don't hesitate, thanks!

**Comment by sharkwouter** [comment]
@taba256's merge request has been merged. There should be a fixed build in about 2 hours from now. Can you try again then?
