### ISSUE TITLE
Missing header in psprtc.h

### ISSUE THREAD

**Issue by Fewnity** [pspdev/pspsdk#155]
I tried to include `psprtc.h` on my project and I found that `psptypes.h` needs to be included before `psprtc.h`. Or you will have some errors about types. 
I think we should add an include of `psptypes.h` in `psprtc.h`, I'm not doing a pullrequest because I can't test if this can cause some problems when compiling the sdk.

**Comment by sharkwouter** [comment]
Thanks for the report. This should be pretty easy to fix. Do you have a code example which shows this issue?

**Comment by sharkwouter** [comment]
This has been fixed in the GitHub repo now. Can you try again in a couple of hours from now? Then the build should be done.
