### ISSUE TITLE
Missing `remove(const char *path)`

### ISSUE THREAD

**Issue by glebm** [pspdev/pspsdk#161]
The `remove` function from stdio appears to be missing.

The implementation could probably be a wrapper around `__set_errno(sceIoRemove(path))`.

E.g. PS2 SDK does this:
https://github.com/ps2dev/ps2sdk/blob/6b656d1ae18dd2bb75a6caa03346cf9f933c12c6/ee/libcglue/src/glue.c#L576C17-L582

Whereas the PSP SDK currently stubs out the `_unlink` function (called by `remove`) to always fail:

https://github.com/pspdev/pspsdk/blob/2f723c3b8280100c1d77d74d23e37d58f7423506/src/libcglue/glue.c#L603-L608

**Comment by fjtrujy** [comment]
Yes, you are right!
I will fix it today!

**Comment by fjtrujy** [comment]
PR ready! https://github.com/pspdev/pspsdk/pull/162

**Comment by glebm** [comment]
Thank you!
