### ISSUE TITLE
configure doesn't set default CFLAGS

### ISSUE THREAD

**Issue by rofl0r** [pspdev/pspsdk#190]
usually when using autoconf-based configure scripts, the expectation is that when no CFLAGS are passed by the user (via command line or environment variables), the default of "-O2 -g" is used. this is currently not the case with the configure script. therefore, if the SDK is built without setting CFLAGS externally, no optimization nor debug info is available.

**Comment by diamant3** [comment]
I think there's a related discussions on that one, please check here: https://github.com/pspdev/pspdev/discussions/57, hopefully it fits to you

**Comment by rofl0r** [comment]
odd, last time i didn't set my own CFLAGS="-O2 -g", stuff was built without debug info, i had to recompile the sdk because psplinkusb jumps into nirvana if crt0.o has no debug info.

**Comment by rofl0r** [comment]
according to https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Preset-Output-Variables.html AC_PROG_CC sets the default CFLAGS. i checked the makefile and indeed -O2 -2 is there now. i wonder what went wrong when crt*.o was built without -g? anyway this seems to be fixed.
