### ISSUE TITLE
libpspdmac doesn't work

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/pspsdk#214]
To use the SceDmacMemcpy function you need to include `pspdmac.h` and link to libpspdmac. When I then try to use the function, I see the following error while linking:
```
(.text+0xae84): undefined reference to `_Z13sceDmacMemcpyPvPKvj'
```

So it seems right now this function is unusable.

**Comment by diamant3** [comment]
have you tried just the `pspdmac`?
