### ISSUE TITLE
build_prx.mak: -mno-crt0 option doesn’t exist in current psp-gcc

### ISSUE THREAD

**Issue by ticky** [pspdev/pspsdk#24]
`-mno-crt0` does not exist in current versions of psp-gcc installed by the toolchain.

[`build_prx.mak` is still dependent on this flag](https://github.com/pspdev/pspsdk/blob/300ec5c405d7c41d43c6735c5897aa80c731b7c0/src/base/build_prx.mak#L32), and for plugins whose makefiles inherit from it correctly, this causes building them to fail.

This appears to be a long-standing issue, with no satisfactory solution given: pspdev/psptoolchain#72, pspdev/psptoolchain#78

**Comment by fjtrujy** [comment]
Hello,
Still suffering this issue, why this PR is not merged?

Thanks
