### ISSUE TITLE
Latest master doesn't compile if using WSL2 Ubuntu 24.0.4 official release

### ISSUE THREAD

**Issue by thearchivalone** [pspdev/pspsdk#254]
### Description of Bug

PSPSDK fails to build due to `zlib.h` not being found

### How to Reproduce

1) Configure WSL2 on Windows
2) Install / upgrade to Ubuntu 24.0.4
3) Clone branch from repo
4) Build and install all required prerequisites
5) Run through the build process

### Why Does This Happen

The `build-essential` package at one time installed the `zlib-dev` package by default. 24.0.4 switched the package to `zlib1g-dev` and removed it from `build-essential`.

### Suggested Fix

Add a note to the documentation about this so that other people know to install the missing package before building. It's the only one like this. This issue was opened mostly to document that in case others run into the same issue.

Thanks for your time.

**Comment by sharkwouter** [comment]
It does seem like the virtual package `libz-dev` still exists. We could use that.

**Comment by diamant3** [comment]
> It does seem like the virtual package libz-dev still exists. We could use that.

Nice. If that's the case, I'll make a PR for that.

**Comment by thearchivalone** [comment]
> > It does seem like the virtual package libz-dev still exists. We could use that.
> 
> Nice. If that's the case, I'll make a PR for that.

Very nice. I rarely use Ubuntu like this and forgot about virtual packages. That should help with backwards compatibility, right?

**Comment by sharkwouter** [comment]
Exactly, then we don't have to specify a version and it works with older systems too.

**Comment by thearchivalone** [comment]
I don't see anything else here. This is closeable for me unless there's something I missed.

**Comment by sharkwouter** [comment]
Great! Thanks for reporting this
