### ISSUE TITLE
VFPU lv.q and ulv.q

### ISSUE THREAD

**Issue by mills32** [pspdev/pspsdk#30]
Hi, I read PSP 1000 has a problem in the VFPU, it looks like the instruction "ulv.q" is broken. Is that true?.

I could replace ulv with lv in some functions, like the "look at", which calculates the view matrix for the camera. But it seems to cause a lot of truoble and crashes in functions to translate, rotate and scale matrix (on my psp 2000 and on ppsspp emulator).

I also read lv needs aligned data to work, so I tried to add "__attribute__((aligned(16)))" to function parameters. This only worked with the "look at" function.

I'd really like to know more about this, and why lv crashes so much.

Thanks.

**Comment by albe** [comment]
> I read PSP 1000 has a problem in the VFPU, it looks like the instruction "ulv.q" is broken. Is that true?.

I didn't remember, but that seems to be true as of this thread: http://lukasz.dk/mirror/forums.ps2dev.org/viewtopicf96b.html
What hlide wrote there is absolutely trustworthy, as we both digged into the VFPU instructions back then. He was maybe one of the most experienced homebrew devs around regarding VFPU code.

> I'd really like to know more about this, and why lv crashes so much.

As you stated, `lv` is an aligned access operation. Trying to access unaligned memory with that operation will inevitably crash. So you need to make sure every memory location accessed through those ops is correctly aligned. The biggest issue is probably the stack variables.

**Comment by mills32** [comment]
Thanks a lot!.
Then I'll have to get rid of all "ulv" and use lv. I'll test all possible alignments with __attribute__((aligned(value))).

It helps a lot that PPSSPP is emulating the psp so well, that "lv" crashes like the real console, if not used properly.
