### ISSUE TITLE
Mip Mapping sample

### ISSUE THREAD

**Issue by mills32** [pspdev/pspsdk#31]
I spent a few days trying to make this work because there was little info about it on the internet. Also pspsdk did not have a sample code for this. 

So here it is, a mip mapping sample :).

[MIPMAPPING.zip](https://github.com/pspdev/pspsdk/files/3377912/MIPMAPPING.zip)

**Comment by wally4000** [comment]
Could you please submit this as a pull request? 👍

**Comment by mills32** [comment]
Yes, but... I don't really know how to do it.

**Comment by wally4000** [comment]
PR #44 Submitted, sample approved. Thanks :)
