### ISSUE TITLE
List of possible contributions.

### ISSUE THREAD

**Issue by Sir-Fortesque** [pspdev/pspsdk#33]
I've noticed a lot more interest in the pspsdk recently, which is fantastic.

I wanted to open up a conversation about a list of required/wanted contributions. I would like to contribute more to this project but not sure where I should put my resources.

I've started on working on compiling libcurl, specifically with SSL. I know at one point libcurl was available https://github.com/jdek/jim-pspware however is quite old so I will be moving to a more recent version.

**Comment by sharkwouter** [comment]
Porting or updating libraries is a good place to start for sure. Check out the psplibraries repo. There is a todo list for the toolchain in General here: https://github.com/pspdev/psptoolchain/projects/1

You should probably join discord as well: https://discord.gg/bePrj9W

**Comment by Sir-Fortesque** [comment]
I missed the projects board for the psptoolchain, thanks for the link. I've also joined the discord.

**Comment by wally4000** [comment]
Closing as resolved
