### ISSUE TITLE
profiler crash

### ISSUE THREAD

**Issue by darksectordds** [pspdev/pspsdk#43]
In my PSP Go 6.60 [Model: 5g] i can't get the sample to work from /samples/debug/profiler. Even the usual attempt to access the main address forces the crash.

Example:
```c++
PSP_MODULE_INFO("Profiler test", 0x1000, 1, 1);

/* main */
pspKernelSetKernelPC();
PspDebugProfilerRegs* prof_regs = (PspDebugProfilerRegs*)PROFILER_REG_BASE; // crash here!
```

Similarly, the function of enabling and disabling the Profiler, because it uses the same address.

Does this even work for anyone? Yes, I still think that something is cut in the PSP Go. One way you need to somehow get access to the Profiler, because the optimization problem has long been a problem when creating homebrew on the PSP. I try to dig in this direction, but so far I haven't found anything useful.

Sorry for my bad English.

**Comment by sajattack** [comment]
Closing this, the info has been moved into tracking issue #45, where we will work on all the samples that are broken.
