### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Florin9doi** [pspdev/pspsdk#47]
https://github.com/pspdev/pspsdk/blob/e0cdfa27b9ec2832a72376fff32af55fc9f316da/src/usb/pspusb.h#L40

> @param size - Size of arguments to pass to USB driver ~~start~~ stop
> @param args - Arguments to pass to USB driver ~~start~~ stop

**Comment by sharkwouter** [comment]
Good catch, do you know how to make a pull request?
