### ISSUE TITLE
Missing sprintf and friends

### ISSUE THREAD

**Issue by glebm** [pspdev/pspsdk#53]
`sprintf` is used extensively in DevilutionX (Diablo 1)

/cc @AJenbo

**Comment by glebm** [comment]
Nevermind, user error

**Comment by AJenbo** [comment]
Well, the friends are still missing, but that seems to be "by design" :D

**Comment by glebm** [comment]
I've filed an issue in the libc that's actually the one that's used https://github.com/pspdev/newlib/issues/2
