### ISSUE TITLE
Some resource leaks

### ISSUE THREAD

**Issue by ryancaicse** [pspdev/pspsdk#80]
File  `fp` is not closed at  Line 135 and 142
https://github.com/pspdev/pspsdk/blob/d019dbc7ecc198102229d0cdfe02976b6bef4e4d/tools/psp-prxgen.c#L125-L146

**Comment by ryancaicse** [comment]
File `fp` is not closed at Line 186 and 193
https://github.com/pspdev/pspsdk/blob/d019dbc7ecc198102229d0cdfe02976b6bef4e4d/tools/psp-fixup-imports.c#L176-L197

**Comment by ryancaicse** [comment]
File source is not closed at Line 365 and 370
https://github.com/pspdev/pspsdk/blob/d019dbc7ecc198102229d0cdfe02976b6bef4e4d/tools/bin2o.c#L347-L372

**Comment by ryancaicse** [comment]
Files infile and outfile are not closed at the erroneous returns
https://github.com/pspdev/pspsdk/blob/d019dbc7ecc198102229d0cdfe02976b6bef4e4d/tools/unpack-pbp.c#L83-L156

**Comment by ryancaicse** [comment]
File source is not closed at Line 43 and 48

https://github.com/pspdev/pspsdk/blob/d019dbc7ecc198102229d0cdfe02976b6bef4e4d/tools/bin2s.c#L30-L50

**Comment by mrneo240** [comment]
most modern sane toolchains flush and close file handles on clean exit or return from main.

**Comment by wally4000** [comment]
Wouldn't it be worth fixing these to just be compliant anyway? Considering these tools are compiled for the host

Could you please submit a pull request @ryancaicse as it will gather more interest.

**Comment by ryancaicse** [comment]
OK, please check
